### PR TITLE
Use stub binaries from esptool.py v4.5.dev1-2-g32e801484

### PR DESCRIPTION
**Pull request by igrr**
- Update the stubs, fixing the issue that the stub was not responding after uploading over USB_SERIAL_JTAG (https://github.com/espressif/esptool-js/issues/41#issuecomment-1380763991)
- Use original unmodified stub json files from esptool, simplifying future updates.
- Bundle the json files and import them into target-specific files.
- Note: stub text segment is no longer compressed, which increases the distribution size, somewhat. However this should be mitigated if the bundle is gzipped.

## Testing

Can be tested at https://igrr.github.io/esptool-js/.

I've tested this on:

- [x] ESP32 with FT2232
- [x] ESP32-C3 with CP2102
- [x] ESP32-C3 with USB_SERIAL_JTAG
- [x] ESP32-S3 with USB_SERIAL_JTAG
- [x] ESP32-S2 with CP2102
- [ ] ESP32-S2 with built-in USB_CDC — fails, but also fails in the `main` branch (https://github.com/espressif/esptool-js/issues/38)

Tested by connecting and flashing a single 1.3 MB binary.

### CODE REVIEW

**Comment by liux-pro** [comment]
Please note that recently there is an issue about esptool-v4.4, esp32s3, stub firmware.
esptool-v4.4 may be unstable.
https://github.com/espressif/esp-idf/issues/10431

**Comment by igrr** [comment]
I see, thanks for the heads-up. I might downgrade to v4.3 then since v4.5 isn't released yet.

**Review by brianignacio5 — APPROVED** [review]
PR LGTM !

**Comment by igrr** [comment]
After checking with esptool.py maintainers, have decided to upgrade to the latest commit https://github.com/espressif/esptool/commit/32e80148493a83d34bad635287cb97e458d2af58. It fixes one issue with the stub for USB_SERIAL_JTAG.

**Comment by igrr** [comment]
Have re-tested with the new stub, seems to work okay. I have one ESP32-S3 board with a CP2102 with which I get a timeout during flashing, but another similar ESP32-S3 & CP2102 board works fine. I think I'll merge this anyway, and investigate that issue separately (it might be the same as https://github.com/espressif/esptool-js/issues/47).

**Pull request merged**
