### PR TITLE
Allow reporting progress

### PR DESCRIPTION
**Pull request by balloob**
This allows passing a callback into write_flash to report progress.

### CODE REVIEW

**Comment by adwait-esp** [comment]
I don't see the callback function definition anywhere, or is it just a provision for now?

**Comment by balloob** [comment]
It's an optional callback. For testing purposes I added one to index.js but I didn't commit that. Let me add a nice progress bar to the HTML.

**Comment by adwait-esp** [comment]
LGTM

**Comment by balloob** [comment]
Progress bar added to the website in #30

**Pull request merged**
